"""Entity definitions for HA MQTT Discovery.

Each EntityDef maps one HA entity to a key in the poller's merged Sample.points
dict.  The controller's read_*_status() methods return pre-scaled values, so
stat_key values here match those dict keys directly.

Slug, ha_type, and unique_id format are immutable once published (AP-2 policy
from the HA integrator).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class EntityDef:
    slug: str
    name: str
    ha_type: str
    state_group: str
    stat_key: str = ""

    unit: str = ""
    device_class: str = ""
    state_class: str = ""
    icon: str = ""
    entity_category: str = ""

    value_scale: float = 1.0
    value_precision: int | None = None

    # Phase gating: None = always publish, 1/2/3 = only for ACType >= phase-1
    # phase=1 → single/split/three, phase=2 → split/three, phase=3 → three only
    phase: int | None = None

    # SunSpec source: model.point notation (e.g. "701.W", "ext.15506", "virtual")
    source: str = ""

    is_control: bool = False
    options: list[str] = field(default_factory=list)
    min_val: float | None = None
    max_val: float | None = None
    step: float | None = None

    def format_value(self, raw_value: float | int | str) -> str:
        if isinstance(raw_value, str):
            return raw_value
        if self.value_scale == 1.0 and self.value_precision is None:
            return str(raw_value)
        scaled = raw_value * self.value_scale
        if self.value_precision is not None:
            return f"{scaled:.{self.value_precision}f}"
        return str(scaled)

    def unique_id(self, short_id: str) -> str:
        return f"franklinwh_{short_id}_{self.slug}"

    def state_topic(self, short_id: str) -> str:
        return f"franklinwh/{short_id}/{self.state_group}/{self.slug}"

    def command_topic(self, short_id: str) -> str | None:
        if self.is_control:
            return f"franklinwh/{short_id}/control/{self.slug}/set"
        return None

    def discovery_topic(self, short_id: str) -> str:
        return f"homeassistant/{self.ha_type}/franklinwh_{short_id}_{self.slug}/config"


# ---------------------------------------------------------------------------
# Entity registry — maps controller read method keys → HA entities
#
# stat_key corresponds to keys in Sample.points, which are populated by
# ModbusPoller merging read_battery_status(), read_grid_status(),
# read_solar_status(), read_control_status(), read_native_mode().
# ---------------------------------------------------------------------------

BRIDGE_ENTITIES: list[EntityDef] = [
    # === BATTERY (from read_battery_status) ===
    EntityDef(
        slug="battery_soc",
        name="State of Charge",
        ha_type="sensor",
        state_group="battery",
        stat_key="soc",
        unit="%",
        device_class="battery",
        state_class="measurement",
        icon="mdi:battery",
        source="713.SoC",
    ),
    EntityDef(
        slug="battery_soh",
        name="State of Health",
        ha_type="sensor",
        state_group="battery",
        stat_key="soh",
        unit="%",
        state_class="measurement",
        icon="mdi:battery-heart-variant",
        source="713.SoH",
    ),
    EntityDef(
        slug="battery_power_kw",
        name="Battery Power",
        ha_type="sensor",
        state_group="battery",
        stat_key="battery_power_w",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:battery-charging",
        value_scale=0.001,
        value_precision=3,
        source="714.DCW",
    ),
    EntityDef(
        slug="battery_current_a",
        name="Battery Current",
        ha_type="sensor",
        state_group="battery",
        stat_key="battery_current_a",
        unit="A",
        device_class="current",
        state_class="measurement",
        icon="mdi:current-dc",
        value_precision=1,
        source="714.DCA",
    ),
    EntityDef(
        slug="battery_temp_c",
        name="Battery Temperature",
        ha_type="sensor",
        state_group="battery",
        stat_key="battery_temp_c",
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        icon="mdi:thermometer",
        value_precision=1,
        source="714.Tmp",
    ),
    EntityDef(
        slug="battery_state",
        name="Battery State",
        ha_type="sensor",
        state_group="battery",
        stat_key="battery_state",
        icon="mdi:battery-sync",
        source="714.DCW",
    ),
    EntityDef(
        slug="battery_health",
        name="Battery Health",
        ha_type="sensor",
        state_group="battery",
        stat_key="battery_health",
        icon="mdi:battery-heart-variant",
        entity_category="diagnostic",
        source="713.Sta",
    ),
    EntityDef(
        slug="total_capacity_kwh",
        name="Total Capacity",
        ha_type="sensor",
        state_group="capacity",
        stat_key="wh_rating",
        unit="kWh",
        icon="mdi:battery-high",
        state_class="measurement",
        entity_category="diagnostic",
        value_scale=0.001,
        value_precision=3,
        source="713.WHRtg",
    ),
    EntityDef(
        slug="available_capacity_kwh",
        name="Available Capacity",
        ha_type="sensor",
        state_group="capacity",
        stat_key="wh_available",
        unit="kWh",
        icon="mdi:battery-50",
        state_class="measurement",
        value_scale=0.001,
        value_precision=3,
        source="713.WHAvail",
    ),
    EntityDef(
        slug="max_charge_rate_kw",
        name="Max Charge Rate",
        ha_type="sensor",
        state_group="capacity",
        stat_key="max_charge_rate_w",
        unit="kW",
        device_class="power",
        icon="mdi:battery-arrow-up",
        entity_category="diagnostic",
        value_scale=0.001,
        value_precision=1,
        source="702.WChaRteMaxRtg",
    ),
    EntityDef(
        slug="max_discharge_rate_kw",
        name="Max Discharge Rate",
        ha_type="sensor",
        state_group="capacity",
        stat_key="max_discharge_rate_w",
        unit="kW",
        device_class="power",
        icon="mdi:battery-arrow-down",
        entity_category="diagnostic",
        value_scale=0.001,
        value_precision=1,
        source="702.WDisChaRteMaxRtg",
    ),

    # === GRID / AC (from read_grid_status) ===
    EntityDef(
        slug="grid_power_kw",
        name="Grid Power",
        ha_type="sensor",
        state_group="power",
        stat_key="grid_power_w",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:transmission-tower",
        value_scale=0.001,
        value_precision=3,
        source="701.W",
    ),
    EntityDef(
        slug="grid_voltage_v",
        name="Grid Voltage",
        ha_type="sensor",
        state_group="status",
        stat_key="voltage_v",
        unit="V",
        device_class="voltage",
        state_class="measurement",
        icon="mdi:flash",
        source="701.LNV",
    ),
    EntityDef(
        slug="grid_frequency_hz",
        name="Frequency",
        ha_type="sensor",
        state_group="status",
        stat_key="frequency_hz",
        unit="Hz",
        device_class="frequency",
        state_class="measurement",
        icon="mdi:sine-wave",
        source="701.Hz",
    ),
    EntityDef(
        slug="grid_current_a",
        name="Grid Current",
        ha_type="sensor",
        state_group="status",
        stat_key="current_a",
        unit="A",
        device_class="current",
        state_class="measurement",
        icon="mdi:current-ac",
        source="701.A",
    ),
    EntityDef(
        slug="grid_apparent_power_va",
        name="Apparent Power",
        ha_type="sensor",
        state_group="status",
        stat_key="grid_va",
        unit="VA",
        device_class="apparent_power",
        state_class="measurement",
        icon="mdi:flash-triangle",
        source="701.VA",
    ),
    EntityDef(
        slug="grid_reactive_power_var",
        name="Reactive Power",
        ha_type="sensor",
        state_group="status",
        stat_key="grid_var",
        unit="var",
        device_class="reactive_power",
        state_class="measurement",
        icon="mdi:math-sin",
        source="701.Var",
    ),
    EntityDef(
        slug="grid_power_factor",
        name="Power Factor",
        ha_type="sensor",
        state_group="status",
        stat_key="power_factor",
        device_class="power_factor",
        state_class="measurement",
        icon="mdi:angle-acute",
        source="701.PF",
    ),
    EntityDef(
        slug="grid_connection_state",
        name="Grid Connection",
        ha_type="sensor",
        state_group="status",
        stat_key="connection_state",
        icon="mdi:transmission-tower-import",
        entity_category="diagnostic",
        source="701.ConnSt",
    ),
    EntityDef(
        slug="inverter_state",
        name="Inverter State",
        ha_type="sensor",
        state_group="status",
        stat_key="inverter_state",
        icon="mdi:power-settings",
        entity_category="diagnostic",
        source="701.InvSt",
    ),
    EntityDef(
        slug="grid_export_kwh",
        name="Grid Export Energy",
        ha_type="sensor",
        state_group="energy",
        stat_key="grid_export_wh",
        unit="kWh",
        device_class="energy",
        state_class="total_increasing",
        icon="mdi:transmission-tower-export",
        value_scale=0.001,
        value_precision=3,
        source="701.TotWhInj",
    ),
    EntityDef(
        slug="grid_import_kwh",
        name="Grid Import Energy",
        ha_type="sensor",
        state_group="energy",
        stat_key="grid_import_wh",
        unit="kWh",
        device_class="energy",
        state_class="total_increasing",
        icon="mdi:transmission-tower-import",
        value_scale=0.001,
        value_precision=3,
        source="701.TotWhAbs",
    ),

    # === PER-PHASE AC (auto-detected from M701 ACType) ===
    # phase=1 → always (single/split/three), phase=2 → split+three, phase=3 → three only

    # ── L1 (phase 1) ──────────────────────────────────────
    EntityDef(
        slug="grid_voltage_l1_v",
        name="Voltage L1",
        ha_type="sensor",
        state_group="status",
        stat_key="voltage_l1_v",
        unit="V",
        device_class="voltage",
        state_class="measurement",
        icon="mdi:flash",
        phase=1,
        source="701.VL1",
    ),
    EntityDef(
        slug="grid_current_l1_a",
        name="Current L1",
        ha_type="sensor",
        state_group="status",
        stat_key="current_l1_a",
        unit="A",
        device_class="current",
        state_class="measurement",
        icon="mdi:current-ac",
        phase=1,
        source="701.AL1",
    ),
    EntityDef(
        slug="grid_power_l1_w",
        name="Power L1",
        ha_type="sensor",
        state_group="power",
        stat_key="power_l1_w",
        unit="W",
        device_class="power",
        state_class="measurement",
        icon="mdi:flash",
        phase=1,
        source="701.WL1",
    ),
    EntityDef(
        slug="grid_pf_l1",
        name="Power Factor L1",
        ha_type="sensor",
        state_group="status",
        stat_key="pf_l1",
        device_class="power_factor",
        state_class="measurement",
        icon="mdi:angle-acute",
        phase=1,
        source="701.PFL1",
    ),
    EntityDef(
        slug="grid_va_l1",
        name="Apparent Power L1",
        ha_type="sensor",
        state_group="status",
        stat_key="va_l1",
        unit="VA",
        device_class="apparent_power",
        state_class="measurement",
        icon="mdi:flash-triangle",
        phase=1,
        source="701.VAL1",
    ),
    EntityDef(
        slug="grid_var_l1",
        name="Reactive Power L1",
        ha_type="sensor",
        state_group="status",
        stat_key="var_l1",
        unit="var",
        device_class="reactive_power",
        state_class="measurement",
        icon="mdi:math-sin",
        phase=1,
        source="701.VarL1",
    ),

    # ── L2 (phase 2 — split + three-phase) ────────────────
    EntityDef(
        slug="grid_voltage_l2_v",
        name="Voltage L2",
        ha_type="sensor",
        state_group="status",
        stat_key="voltage_l2_v",
        unit="V",
        device_class="voltage",
        state_class="measurement",
        icon="mdi:flash",
        phase=2,
        source="701.VL2",
    ),
    EntityDef(
        slug="grid_current_l2_a",
        name="Current L2",
        ha_type="sensor",
        state_group="status",
        stat_key="current_l2_a",
        unit="A",
        device_class="current",
        state_class="measurement",
        icon="mdi:current-ac",
        phase=2,
        source="701.AL2",
    ),
    EntityDef(
        slug="grid_power_l2_w",
        name="Power L2",
        ha_type="sensor",
        state_group="power",
        stat_key="power_l2_w",
        unit="W",
        device_class="power",
        state_class="measurement",
        icon="mdi:flash",
        phase=2,
        source="701.WL2",
    ),
    EntityDef(
        slug="grid_pf_l2",
        name="Power Factor L2",
        ha_type="sensor",
        state_group="status",
        stat_key="pf_l2",
        device_class="power_factor",
        state_class="measurement",
        icon="mdi:angle-acute",
        phase=2,
        source="701.PFL2",
    ),
    EntityDef(
        slug="grid_va_l2",
        name="Apparent Power L2",
        ha_type="sensor",
        state_group="status",
        stat_key="va_l2",
        unit="VA",
        device_class="apparent_power",
        state_class="measurement",
        icon="mdi:flash-triangle",
        phase=2,
        source="701.VAL2",
    ),
    EntityDef(
        slug="grid_var_l2",
        name="Reactive Power L2",
        ha_type="sensor",
        state_group="status",
        stat_key="var_l2",
        unit="var",
        device_class="reactive_power",
        state_class="measurement",
        icon="mdi:math-sin",
        phase=2,
        source="701.VarL2",
    ),
    EntityDef(
        slug="grid_voltage_l1l2_v",
        name="Voltage L1-L2",
        ha_type="sensor",
        state_group="status",
        stat_key="voltage_l1l2_v",
        unit="V",
        device_class="voltage",
        state_class="measurement",
        icon="mdi:flash",
        phase=2,
        source="701.VL1L2",
    ),

    # ── L3 (phase 3 — three-phase only) ───────────────────
    EntityDef(
        slug="grid_voltage_l3_v",
        name="Voltage L3",
        ha_type="sensor",
        state_group="status",
        stat_key="voltage_l3_v",
        unit="V",
        device_class="voltage",
        state_class="measurement",
        icon="mdi:flash",
        phase=3,
        source="701.VL3",
    ),
    EntityDef(
        slug="grid_current_l3_a",
        name="Current L3",
        ha_type="sensor",
        state_group="status",
        stat_key="current_l3_a",
        unit="A",
        device_class="current",
        state_class="measurement",
        icon="mdi:current-ac",
        phase=3,
        source="701.AL3",
    ),
    EntityDef(
        slug="grid_power_l3_w",
        name="Power L3",
        ha_type="sensor",
        state_group="power",
        stat_key="power_l3_w",
        unit="W",
        device_class="power",
        state_class="measurement",
        icon="mdi:flash",
        phase=3,
        source="701.WL3",
    ),
    EntityDef(
        slug="grid_pf_l3",
        name="Power Factor L3",
        ha_type="sensor",
        state_group="status",
        stat_key="pf_l3",
        device_class="power_factor",
        state_class="measurement",
        icon="mdi:angle-acute",
        phase=3,
        source="701.PFL3",
    ),
    EntityDef(
        slug="grid_va_l3",
        name="Apparent Power L3",
        ha_type="sensor",
        state_group="status",
        stat_key="va_l3",
        unit="VA",
        device_class="apparent_power",
        state_class="measurement",
        icon="mdi:flash-triangle",
        phase=3,
        source="701.VAL3",
    ),
    EntityDef(
        slug="grid_var_l3",
        name="Reactive Power L3",
        ha_type="sensor",
        state_group="status",
        stat_key="var_l3",
        unit="var",
        device_class="reactive_power",
        state_class="measurement",
        icon="mdi:math-sin",
        phase=3,
        source="701.VarL3",
    ),
    EntityDef(
        slug="grid_voltage_l2l3_v",
        name="Voltage L2-L3",
        ha_type="sensor",
        state_group="status",
        stat_key="voltage_l2l3_v",
        unit="V",
        device_class="voltage",
        state_class="measurement",
        icon="mdi:flash",
        phase=3,
        source="701.VL2L3",
    ),
    EntityDef(
        slug="grid_voltage_l3l1_v",
        name="Voltage L3-L1",
        ha_type="sensor",
        state_group="status",
        stat_key="voltage_l3l1_v",
        unit="V",
        device_class="voltage",
        state_class="measurement",
        icon="mdi:flash",
        phase=3,
        source="701.VL3L1",
    ),

    # === TEMPERATURES (from read_grid_status) ===
    EntityDef(
        slug="ambient_temp_c",
        name="Ambient Temperature",
        ha_type="sensor",
        state_group="status",
        stat_key="ambient_temp_c",
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        icon="mdi:thermometer",
        entity_category="diagnostic",
        source="701.TmpAmb",
    ),
    EntityDef(
        slug="cabinet_temp_c",
        name="Cabinet Temperature",
        ha_type="sensor",
        state_group="status",
        stat_key="cabinet_temp_c",
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        icon="mdi:thermometer",
        entity_category="diagnostic",
        source="701.TmpCab",
    ),

    # === SOLAR (from read_solar_status) ===
    EntityDef(
        slug="solar_power_kw",
        name="Solar Power",
        ha_type="sensor",
        state_group="solar",
        stat_key="ac_power_w",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:solar-power",
        value_scale=0.001,
        value_precision=3,
        source="502.OutPw",
    ),

    # === EXTENSION REGISTERS (from read_solar_status → extension) ===
    EntityDef(
        slug="home_load_kw",
        name="Home Load",
        ha_type="sensor",
        state_group="power",
        stat_key="home_load_ext",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:home-lightning-bolt",
        value_scale=0.001,
        value_precision=3,
        source="ext.16000",
    ),
    EntityDef(
        slug="pv_total_kw",
        name="PV Total Power",
        ha_type="sensor",
        state_group="solar",
        stat_key="pv_total",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:solar-power-variant",
        value_scale=0.001,
        value_precision=3,
        source="ext.15502",
    ),
    EntityDef(
        slug="pv_proximal_kw",
        name="Solar Proximal",
        ha_type="sensor",
        state_group="solar",
        stat_key="pv_proximal",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:solar-panel",
        value_scale=0.001,
        value_precision=3,
        source="ext.15503",
    ),
    EntityDef(
        slug="pv_remote1_kw",
        name="Solar Remote 1",
        ha_type="sensor",
        state_group="solar",
        stat_key="pv_remote1",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:solar-panel",
        value_scale=0.001,
        value_precision=3,
        source="ext.15504",
    ),
    EntityDef(
        slug="pv_remote2_kw",
        name="Solar Remote 2",
        ha_type="sensor",
        state_group="solar",
        stat_key="pv_remote2",
        unit="kW",
        device_class="power",
        state_class="measurement",
        icon="mdi:solar-panel",
        value_scale=0.001,
        value_precision=3,
        source="ext.15505",
    ),

    # === ENERGY COUNTERS (from M714 + extension reg 15510) ===
    EntityDef(
        slug="pv_energy_total_kwh",
        name="Solar Energy Total",
        ha_type="sensor",
        state_group="energy",
        stat_key="pv_energy_total_wh",
        unit="kWh",
        device_class="energy",
        state_class="total_increasing",
        icon="mdi:solar-power-variant",
        value_scale=0.001,
        value_precision=2,
        source="ext.15510",
    ),
    EntityDef(
        slug="battery_energy_discharged_kwh",
        name="Battery Energy Discharged",
        ha_type="sensor",
        state_group="energy",
        stat_key="dc_energy_discharged_wh",
        unit="kWh",
        device_class="energy",
        state_class="total_increasing",
        icon="mdi:battery-arrow-up",
        value_scale=0.001,
        value_precision=2,
        source="714.DCWhInj",
    ),
    EntityDef(
        slug="battery_energy_charged_kwh",
        name="Battery Energy Charged",
        ha_type="sensor",
        state_group="energy",
        stat_key="dc_energy_charged_wh",
        unit="kWh",
        device_class="energy",
        state_class="total_increasing",
        icon="mdi:battery-arrow-down",
        value_scale=0.001,
        value_precision=2,
        source="714.DCWhAbs",
    ),

    # === OPERATING MODE (from read_native_mode) ===
    EntityDef(
        slug="operating_mode_sensor",
        name="Operating Mode",
        ha_type="sensor",
        state_group="status",
        stat_key="mode_name",
        icon="mdi:cog-outline",
        entity_category="diagnostic",
        source="ext.15507",
    ),

    # === CONTROL (from read_control_status) ===
    EntityDef(
        slug="control_mode",
        name="Control Mode",
        ha_type="sensor",
        state_group="status",
        stat_key="loc_rem_ctl_name",
        icon="mdi:remote",
        entity_category="diagnostic",
        source="715.LocRemCtl",
    ),
    EntityDef(
        slug="wset_enabled",
        name="WSet Enabled",
        ha_type="binary_sensor",
        state_group="status",
        stat_key="wset_enabled",
        icon="mdi:toggle-switch",
        entity_category="diagnostic",
        source="704.WSetEna",
    ),
    EntityDef(
        slug="power_setpoint_kw",
        name="Power Setpoint",
        ha_type="sensor",
        state_group="status",
        stat_key="wset_watts",
        unit="kW",
        device_class="power",
        icon="mdi:target",
        entity_category="diagnostic",
        value_scale=0.001,
        value_precision=3,
        source="704.WSet",
    ),
    EntityDef(
        slug="wset_mode",
        name="WSet Mode",
        ha_type="sensor",
        state_group="status",
        stat_key="wset_mode_name",
        icon="mdi:cog-transfer",
        entity_category="diagnostic",
        source="704.WSetMod",
    ),
    EntityDef(
        slug="wset_pct",
        name="Power Setpoint %",
        ha_type="sensor",
        state_group="status",
        stat_key="wset_pct",
        unit="%",
        state_class="measurement",
        icon="mdi:percent",
        entity_category="diagnostic",
        source="704.WSetPct",
    ),
    EntityDef(
        slug="hw_revert_time_s",
        name="HW Revert Timer",
        ha_type="sensor",
        state_group="status",
        stat_key="wset_revert_time_s",
        unit="s",
        device_class="duration",
        icon="mdi:timer-cog-outline",
        entity_category="diagnostic",
        source="704.WSetRvrtTms",
    ),
    EntityDef(
        slug="hw_revert_remain_s",
        name="HW Revert Remaining",
        ha_type="sensor",
        state_group="status",
        stat_key="wset_revert_remain_s",
        unit="s",
        device_class="duration",
        icon="mdi:timer-sand",
        entity_category="diagnostic",
        source="704.WSetRvrtRem",
    ),

    # === SOFTWARE TIMER (from CommandHandler virtual points) ===
    EntityDef(
        slug="sw_watchdog_remain_s",
        name="SW Watchdog Remaining",
        ha_type="sensor",
        state_group="status",
        stat_key="sw_watchdog_remain_s",
        unit="s",
        device_class="duration",
        icon="mdi:timer-alert-outline",
        entity_category="diagnostic",
        source="virtual",
    ),
    EntityDef(
        slug="command_elapsed_s",
        name="Command Elapsed Time",
        ha_type="sensor",
        state_group="status",
        stat_key="command_elapsed_s",
        unit="s",
        device_class="duration",
        icon="mdi:timer-outline",
        entity_category="diagnostic",
        source="virtual",
    ),
    EntityDef(
        slug="last_command_result",
        name="Last Command Result",
        ha_type="sensor",
        state_group="status",
        stat_key="last_command_result",
        icon="mdi:message-text-outline",
        entity_category="diagnostic",
        source="virtual",
    ),

    # === WRITABLE CONTROLS ===
    EntityDef(
        slug="operating_mode",
        name="Operating Mode",
        ha_type="select",
        state_group="control",
        stat_key="mode_name",
        icon="mdi:cog",
        is_control=True,
        options=["Emergency Backup", "Self-Consumption", "Time of Use"],
        source="ext.15507",
    ),
    EntityDef(
        slug="self_reserve_pct",
        name="Self-Consumption Reserve SOC",
        ha_type="number",
        state_group="control",
        stat_key="self_reserve_pct",
        unit="%",
        icon="mdi:battery-charging-50",
        is_control=True,
        min_val=0,
        max_val=100,
        step=1,
        source="ext.15508",
    ),
    EntityDef(
        slug="tou_reserve_pct",
        name="TOU Reserve SOC",
        ha_type="number",
        state_group="control",
        stat_key="tou_reserve_pct",
        unit="%",
        icon="mdi:battery-clock",
        is_control=True,
        min_val=0,
        max_val=100,
        step=1,
        source="ext.15509",
    ),

    # === BATTERY COMMAND CONTROLS ===
    EntityDef(
        slug="battery_command",
        name="Battery Command",
        ha_type="select",
        state_group="control",
        stat_key="battery_command_state",
        icon="mdi:battery-sync",
        is_control=True,
        options=[
            "Not Active", "Charge", "Discharge",
            "Standby", "Release",
        ],
        source="virtual",
    ),
    EntityDef(
        slug="battery_command_power",
        name="Command Power",
        ha_type="number",
        state_group="control",
        stat_key="battery_command_power_w",
        unit="W",
        device_class="power",
        icon="mdi:flash",
        is_control=True,
        min_val=0,
        max_val=5000,  # default; overridden at runtime from M702 nameplate
        step=100,
        source="virtual",
    ),
    EntityDef(
        slug="battery_command_power_pct",
        name="Command Power %",
        ha_type="number",
        state_group="control",
        stat_key="battery_command_power_pct",
        unit="%",
        icon="mdi:percent-circle",
        is_control=True,
        min_val=0,
        max_val=100,
        step=5,
        source="virtual",
    ),
    EntityDef(
        slug="battery_command_duration",
        name="Command Duration",
        ha_type="number",
        state_group="control",
        stat_key="battery_command_duration_s",
        unit="s",
        device_class="duration",
        icon="mdi:timer-outline",
        is_control=True,
        min_val=0,
        max_val=7200,
        step=60,
        source="virtual",
    ),
    EntityDef(
        slug="battery_command_target_soc",
        name="Target SoC",
        ha_type="number",
        state_group="control",
        stat_key="battery_command_target_soc",
        unit="%",
        icon="mdi:battery-charging-wireless",
        is_control=True,
        min_val=0,
        max_val=100,
        step=5,
        source="virtual",
    ),

]


def get_entity_by_slug(slug: str) -> EntityDef | None:
    for ent in BRIDGE_ENTITIES:
        if ent.slug == slug:
            return ent
    return None
